config/routes.rb
Rails.application.routes.draw do
  	devise_for :users, controllers: { confirmations: 'confirmations' }
  	
  	devise_scope :user do
  		root to: "devise/sessions#new"
	end
	# root to: "static#index"
	# get "/index.html" => "static#index"
	# get "/index2.html" => "static#index2"
	# get "/index3.html" => "static#index3"
	# get "/form.html" => "static#form"
	# get "/form_advanced.html" => "static#form_advanced"
	# get "/tables.html" => "static#tables"
	# get "/tables_dynamic.html" => "static#tables_dynamic"
	# get "/general_elements.html" => "static#general_elements"
	# get "/media_gallery.html" => "static#media_gallery"
	# get "/typography.html" => "static#typography"
	# get "/icons.html" => "static#icons"
	# get "/glyphicons.html" => "static#glyphicons"
	# get "/widgets.html" => "static#widgets"
	# get "/invoice.html" => "static#invoice"
	# get "/inbox.html" => "static#inbox"
	# get "/calendar.html" => "static#calendar"
	# get "/chartjs.html" => "static#chartjs"
	# get "/chartjs2.html" => "static#chartjs2"
	# get "/morisjs.html" => "static#morisjs"
	# get "/echarts.html" => "static#echarts"
	# get "/other_charts.html" => "static#other_charts"
	# get "/fixed_sidebar.html" => "static#fixed_sidebar"
	# get "/fixed_footer.html" => "static#fixed_footer"
	# get "/kitchen_sink" => "static#kitchen_sink"
	# get "/kitchen8_sink" => "static#kitchen8_sink"
  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  	
  	#--- Only for API calls---
	namespace :api, defaults: {format: 'json'} do
		namespace :v1 do
			resources :devices do
				get 'save_data' , :on => :collection
			end
		end
	end

	resources :devices do
		post 'update_user_device', on: :collection
	end

	resources :users do
		get 'assign_device', on: :collection
	end

end

app/models/device.rb
class Device < ApplicationRecord
	has_many :device_data
	has_many :user_devices

	has_many :users, :through => :user_devices

end

app/controllers/api/v1/devices_controller.rb
require 'json'
class Api::V1::DevicesController < ApplicationController

	skip_before_action :verify_authenticity_token, :only => :save_data, if: :json_request?

	def save_data

		if params[:data]
			DeviceDatum.create! device_id:1, temperature: params[:data]
			render :json => {"status": "device found and data updated"}
		else
			render :json => {"status": "please provide data"}
		end

		

		# datapoints
		# u.user_device.first.device.device_data.first.humidity
		
		# if params[:access_token]
		# 	d = Device.where(access_token: params[:access_token]).first
		# 	if d
		# 		# now device is found and we are ready to save data
		# 		device_data = d.device_data.today

		# 		d = {
		# 				id: device_data.last.id.to_s+"_1",
		# 				timestamp: Time.now.getutc.to_i.to_s, 
		# 				temprature: params[:temprature]
		# 			}

		# 		# so today a row is already created 
		# 		# now we need to append the data
		# 		if !device_data.empty?
		# 			device_temperature = device_data.last.temprature

		# 			# construct json data
		# 			# data = {data: [{
		# 			# 			id: device_data.id+"_1", 
		# 			# 			timestamp: Time.now.getutc.to_i.to_s, 
		# 			# 			temperature: 
		# 			# 		}]
		# 			# }

		# 			json_data = JSON.parse(device_temperature)
		# 			json_data["data"] << d

		# 			device_data.last.temprature = json_data
		# 			device_data.last.save

		# 			render :json => {"status": "device found and data updated"}
		# 		else
		# 			# no rows created today so create one
		# 			data = {data: [d]}.to_json
		# 			DeviceDatum.create! device:d, temprature: data
		# 			render :json => {"status": "device found and data updated"}
		# 		end
		# 	else
		# 		head 403
		# 	end
		# else
		# 	head 401
		# end
	end

end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.where(:status => "Active").order(:id)
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
    @device = Device.find params[:id]
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)
    @device.uuid = SecureRandom.uuid

    respond_to do |format|
      if @device.save
        flash[:notice] = "Device created successfully"
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render :show, status: :created, location: @device }
      else
        flash[:notice] = "Shop creation unsuccessful"
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    puts @device.inspect
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { render :index, status: :ok, location: @device }
      else
        format.html { render :index }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update_user_device
    # check that the device is assigned to the observer
    # if not assign it 

    Rails.logger.info("device_ids : "+params[:device_ids].to_s)
    observer = User.find(params[:observer_id])
    observer.device_ids = params[:device_ids]

    # @device_ids = params[:device_ids]
    # @observer = User.find(params[:observer_id])

    # unless @device_ids.blank?
    #   @device_ids.each do |id|
    #     Rails.logger.info("id is : "+id)
    #     if !Device.find(id).users.exists?(params[:observer_id])
    #       @user_device = UserDevice.new
    #       @user_device.user_id = params[:observer_id]
    #       @user_device.device_id = id
    #       @user_device.save
    #     end
    #   end
    # end

    respond_to do |format|
      format.html { redirect_to user_path(current_user.id) }
    end
    


    # if other devices assigned previously are not listed unassign those devices
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.fetch(:device, {}).permit(:name, :model, :device_id, :place, :latitude, :longitude)
    end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_device_list_item.html.erb
<tr>
	<td><%= item.id %></td>
	<td><%=	item.name %></td>
	<td><%= item.model %></td>
	<td><%= item.device_id %></td>
	<td><%= item.place %></td>
	<td>
		<%= link_to 'Show', item , :class => 'btn-info btn'%> &nbsp; 
		<%= link_to 'Edit', edit_device_path(item) , :class => 'btn-info btn'%>	&nbsp; 
        <%= link_to 'Destroy', item, :class => 'btn-danger btn', method: :delete, data: { confirm: 'Are you sure?' } %>
	</td>	
</tr>

app/views/devices/_form.html.erb
<form class="form-horizontal form-label-left">
    <div class="form-group">
        <label class="control-label col-md-2 col-sm-2 col-xs-12">Device name</label>
        <div class="col-md-10 col-sm-10 col-xs-12">
            <%= f.text_field(:name, :class => "form-control")%>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2 col-sm-2 col-xs-12">Model</label>
        <div class="col-md-10 col-sm-10 col-xs-12">
            <%= f.text_field(:model, :class => "form-control")%>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2 col-sm-2 col-xs-12">Place</label>
        <div class="col-md-10 col-sm-10 col-xs-12">
            <%= f.text_field(:place, :class => "form-control")%>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2 col-sm-2 col-xs-12">Device ID</label>
        <div class="col-sm-10 col-xs-12">
            <%= f.text_field(:device_id, :class => "form-control")%>
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2 col-sm-2 col-xs-12">Latitude</label>
        <div class="col-sm-10 col-xs-12">
            <%= f.text_field(:latitude, :class => "form-control")%> 
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2 col-sm-2 col-xs-12">Longitude</label>
        <div class="col-sm-10 col-xs-12">
            <%= f.text_field(:longitude, :class => "form-control")%>    
        </div>
    </div>
</form>

app/views/devices/edit.html.erb
<h1>Editing Device</h1>

<div class="right_col" role="main">
    <div class="row">

        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
					<h2> Device Updation </h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">

                	<%= form_for(:device, :url => {:action => 'update', :id => @device.id}, method: :put ) do |f| %>

						<% @action = "edit" %>
						
					    
					    <div class="row">
					    	<%= render(:partial => "form", :locals => {:f => f}) %>
					    	<div class="col-sm-8 col-sm-offset-2">
							    <br/>
							    <%= submit_tag("Submit", :class => "btn-primary btn") %>
							    <%= link_to 'Back', devices_path %>
							</div>
						</div>
						<br/><br/>
					<% end %>
                	
                </div>
            </div>
        </div>
    </div>
</div>

<%= link_to 'Show', @device %>

app/views/devices/index.html.erb
<p id="notice"><%= notice %></p>
<%#= link_to "Home", user_path(current_user.id), class: "btn-success btn" %>
<h4>Devices</h4>


<table class="table table-striped table-bordered table-hover dataTables-example" >
    <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Model</th>
            <th>Device id</th>
            <th>Place</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @devices.each do |device| %>
            <%= render :partial=>"devices/device_list_item", :locals => {:item => device} %>
        <% end %>
    </tbody>
</table>

<br>

<%= link_to '(+) Create a Device', new_device_path, :class => 'btn-primary btn' %>

app/views/devices/new.html.erb
<h1>New Device</h1>


<div class="right_col" role="main">
    <div class="row">

        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
					<h2> Device Creation </h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">

                	<%= form_for(:device, :url => {:action => 'create', :id => @device.id}) do |f| %>

						<% @action = "new" %>
						
					    
					    <div class="row">

					    	<%= render(:partial => "form", :locals => {:f => f}) %>
					    	<div class="col-sm-8 col-sm-offset-2">
							    <br/>
							    <%= submit_tag("Submit", :class => "btn-primary btn") %>
							    <%= link_to 'Back', devices_path %>
							</div>
						</div>
						<br/><br/>
					<% end %>
                	
                </div>
            </div>
        </div>
    </div>
</div>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<% @page_title = "Device" %>

<div class="right_col" role="main">
    <div class="">
        <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h3> Device <%=@device.id %> </h3>
                        <div class="clearfix"></div>
                        <hr/>
                    </div>
                    <div class="x_content">
                    
                    	<div class="col-md-2 col-sm-3 col-xs-12">
                    		<h4>Device Name  </h4>
                    	</div>
                    	<div class="col-md-10 col-sm-9 col-xs-12">
							<h4> : <%= @device.name %></h4>
                    	</div>
                    
                    	<div class="col-md-2 col-sm-3 col-xs-12">
                    		<h4>Device ID  </h4>
                    	</div>
                    	<div class="col-md-10 col-sm-9 col-xs-12">
							<h4> : <%= @device.device_id %></h4>
                    	</div>
                    
                    	<div class="col-md-2 col-sm-3 col-xs-12">
                    		<h4>Device Model  </h4>
                    	</div>
                    	<div class="col-md-10 col-sm-9 col-xs-12">
							<h4> : <%= @device.model %></h4>
                    	</div>
                    
                    	<div class="col-md-2 col-sm-3 col-xs-12">
                    		<h4>Device Place  </h4>
                    	</div>
                    	<div class="col-md-10 col-sm-9 col-xs-12">
							<h4> : <%= @device.place %></h4>
                    	</div>
                    

                    	<div class="col-md-2 col-sm-3 col-xs-12">
                    		<h4> Status </h4>
                    	</div>
                    	<div class="col-md-10 col-sm-9 col-xs-12">
							<h4> : <%= @device.status %></h4>
                    	</div>

                    	<div class="col-md-2 col-sm-3 col-xs-12">
                    		<h4> Latitude </h4>
                    	</div>
                    	<div class="col-md-10 col-sm-9 col-xs-12">
							<h4> : <%= @device.latitude %></h4>
                    	</div>

                    	<div class="col-md-2 col-sm-3 col-xs-12">
                    		<h4> Longitude </h4>
                    	</div>
                    	<div class="col-md-10 col-sm-9 col-xs-12">
							<h4> : <%= @device.longitude %></h4>
                    	</div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<br>
<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>