config/routes.rb
Rails.application.routes.draw do
  	devise_for :users, controllers: { confirmations: 'confirmations' }
  	
  	devise_scope :user do
  		root to: "devise/sessions#new"
	end
	# root to: "static#index"
	# get "/index.html" => "static#index"
	# get "/index2.html" => "static#index2"
	# get "/index3.html" => "static#index3"
	# get "/form.html" => "static#form"
	# get "/form_advanced.html" => "static#form_advanced"
	# get "/tables.html" => "static#tables"
	# get "/tables_dynamic.html" => "static#tables_dynamic"
	# get "/general_elements.html" => "static#general_elements"
	# get "/media_gallery.html" => "static#media_gallery"
	# get "/typography.html" => "static#typography"
	# get "/icons.html" => "static#icons"
	# get "/glyphicons.html" => "static#glyphicons"
	# get "/widgets.html" => "static#widgets"
	# get "/invoice.html" => "static#invoice"
	# get "/inbox.html" => "static#inbox"
	# get "/calendar.html" => "static#calendar"
	# get "/chartjs.html" => "static#chartjs"
	# get "/chartjs2.html" => "static#chartjs2"
	# get "/morisjs.html" => "static#morisjs"
	# get "/echarts.html" => "static#echarts"
	# get "/other_charts.html" => "static#other_charts"
	# get "/fixed_sidebar.html" => "static#fixed_sidebar"
	# get "/fixed_footer.html" => "static#fixed_footer"
	# get "/kitchen_sink" => "static#kitchen_sink"
	# get "/kitchen8_sink" => "static#kitchen8_sink"
  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  	
  	#--- Only for API calls---
	namespace :api, defaults: {format: 'json'} do
		namespace :v1 do
			resources :devices do
				get 'save_data' , :on => :collection
			end
		end
	end

	resources :devices do
		post 'update_user_device', on: :collection
	end

	resources :users do
		get 'assign_device', on: :collection
	end

end

app/views/shared/_footer.html.erb
<footer>
    <div class="pull-right">
        Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
    </div>
    <div class="clearfix"></div>
</footer>

app/views/shared/_sidenav.html.erb
<div class="col-md-3 left_col">
    <div class="left_col scroll-view " style="height: 100%;">

        <div class="navbar nav_title" style="border: 0;">
            <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>Solar Tracker</span></a>
        </div>
        <div class="clearfix"></div>


        <!-- menu profile quick info -->
        <div class="profile">
            <div class="profile_pic">
                <%= image_tag "user.png", :class => "img-circle profile_img"  %>
            </div>
            <div class="profile_info">
                <span>Welcome,</span>
                <h2><%=current_user.fullname%></h2>
                <!-- <h2>Mike Stifler</h2> -->
            </div>
        </div>
        <!-- /menu profile quick info -->

        <br />

        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">

            <div class="menu_section">
                <h3>&nbsp;</h3>
                <ul class="nav side-menu">
                    <li>
                        <!-- <a href="#"><i class="fa fa-home"></i> Home </a> -->
                        <%= link_to "<i class='fa fa-home'></i><span class='nav-label'> Home<span>".html_safe, user_path(current_user.id)  %>

                        <!-- <a><i class="fa fa-home"></i> Home </a>
                        <ul class="nav child_menu" style="display: none">
                            <li><a href="index.html">Dashboard</a></li>
                            <li><a href="index2.html">Dashboard2</a></li>
                            <li><a href="index3.html">Dashboard3</a></li>
                        </ul> -->
                    </li>
                    <li>
                        <%= link_to "<i class='fa fa-desktop'></i><span class='nav-label'> Devices list<span>".html_safe, devices_path  %>
                        <!-- <a><i class="fa fa-desktop"></i> My Shops </span></a>

                        <ul class="nav child_menu" style="display: none">
                            <li><a href="form.html">General Form</a>
                            </li>
                            <li><a href="form_advanced.html">Advanced Components</a>
                            </li>
                            <li><a href="form_validation.html">Form Validation</a>
                            </li>
                            <li><a href="form_wizards.html">Form Wizard</a>
                            </li>
                            <li><a href="form_upload.html">Form Upload</a>
                            </li>
                            <li><a href="form_buttons.html">Form Buttons</a>
                            </li>
                        </ul> -->
                    </li>
                    <li>

                        <a><i class="fa fa-edit"></i> Edit Profile </a>

                        <ul class="nav child_menu" style="display: none">
                            <li><a href="general_elements.html">General Elements</a>
                            </li>
                            <li><a href="media_gallery.html">Media Gallery</a>
                            </li>
                            <li><a href="typography.html">Typography</a>
                            </li>
                            <li><a href="icons.html">Icons</a>
                            </li>
                            <li><a href="glyphicons.html">Glyphicons</a>
                            </li>
                            <li><a href="widgets.html">Widgets</a>
                            </li>
                            <li><a href="invoice.html">Invoice</a>
                            </li>
                            <li><a href="inbox.html">Inbox</a>
                            </li>
                            <li><a href="calendar.html">Calendar</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a><i class="fa fa-table"></i> Bookings </a>
                        <ul class="nav child_menu" style="display: none">
                            <li><a href="tables.html">Tables</a>
                            </li>
                            <li><a href="tables_dynamic.html">Table Dynamic</a>
                            </li>
                        </ul>
                    </li>
                    <li><a><i class="fa fa-bar-chart-o"></i> Data Analysis</a>
                        <ul class="nav child_menu" style="display: none">
                            <li><a href="chartjs.html">Chart JS</a>
                            </li>
                            <li><a href="chartjs2.html">Chart JS2</a>
                            </li>
                            <li><a href="morisjs.html">Moris JS</a>
                            </li>
                            <li><a href="echarts.html">ECharts </a>
                            </li>
                            <li><a href="other_charts.html">Other Charts </a>
                            </li>
                        </ul>
                    </li>

                    <li>
                        <!-- <a><i class="fa fa-power-off"></i> Logout</a> -->
                        <%= link_to "<i class='fa fa-power-off'></i><span class='nav-label'> Logout<span>".html_safe, destroy_user_session_path , method: :delete %>

                        <!-- <ul class="nav child_menu" style="display: none">
                            <li><a href="chartjs.html">Chart JS</a>
                            </li>
                            <li><a href="chartjs2.html">Chart JS2</a>
                            </li>
                            <li><a href="morisjs.html">Moris JS</a>
                            </li>
                            <li><a href="echarts.html">ECharts </a>
                            </li>
                            <li><a href="other_charts.html">Other Charts </a>
                            </li>
                        </ul> -->
                    </li>

                </ul>
            </div>

        </div>
        <!-- /sidebar menu -->

        <!-- /menu footer buttons -->
        <div class="sidebar-footer hidden-small">
            <a data-toggle="tooltip" data-placement="top" title="Settings">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Lock">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Logout">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
            </a>
        </div>
        <!-- /menu footer buttons -->
    </div>
</div>

app/views/shared/_topbar.html.erb
<div class="top_nav">
    <div class="nav_menu">
        <nav>
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <img src="/images/img.jpg" alt="">Mike Stifler
                        <span class=" fa fa-angle-down"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                        <li><a href="javascript:;"> Profile</a></li>
                        <li>
                            <a href="javascript:;">
                                <span class="badge bg-red pull-right">50%</span>
                                <span>Settings</span>
                            </a>
                        </li>
                        <li><a href="javascript:;">Help</a></li>
                        <li><a href="login.html"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                    </ul>
                </li>

                <li role="presentation" class="dropdown">
                    <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-envelope-o"></i>
                        <span class="badge bg-green">6</span>
                    </a>
                    <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                        <li>
                            <a>
                                <span class="image"><img src="/images/img.jpg" alt="Profile Image" /></span>
                                <span>
                                    <span>John Smith</span>
                                    <span class="time">3 mins ago</span>
                                </span>
                                <span class="message">
                                    Film festivals used to be do-or-die moments for movie makers. They were where...
                                </span>
                            </a>
                        </li>
                        <li>
                            <a>
                                <span class="image"><img src="/images/img.jpg" alt="Profile Image" /></span>
                                <span>
                                    <span>John Smith</span>
                                    <span class="time">3 mins ago</span>
                                </span>
                                <span class="message">
                                    Film festivals used to be do-or-die moments for movie makers. They were where...
                                </span>
                            </a>
                        </li>
                        <li>
                            <a>
                                <span class="image"><img src="/images/img.jpg" alt="Profile Image" /></span>
                                <span>
                                    <span>John Smith</span>
                                    <span class="time">3 mins ago</span>
                                </span>
                                <span class="message">
                                    Film festivals used to be do-or-die moments for movie makers. They were where...
                                </span>
                            </a>
                        </li>
                        <li>
                            <a>
                                <span class="image"><img src="/images/img.jpg" alt="Profile Image" /></span>
                                <span>
                                    <span>John Smith</span>
                                    <span class="time">3 mins ago</span>
                                </span>
                                <span class="message">
                                    Film festivals used to be do-or-die moments for movie makers. They were where...
                                </span>
                            </a>
                        </li>
                        <li>
                            <div class="text-center">
                                <a>
                                    <strong>See All Alerts</strong>
                                    <i class="fa fa-angle-right"></i>
                                </a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</div>