config/routes.rb
Rails.application.routes.draw do
  	devise_for :users, controllers: { confirmations: 'confirmations' }
  	
  	devise_scope :user do
  		root to: "devise/sessions#new"
	end
	# root to: "static#index"
	# get "/index.html" => "static#index"
	# get "/index2.html" => "static#index2"
	# get "/index3.html" => "static#index3"
	# get "/form.html" => "static#form"
	# get "/form_advanced.html" => "static#form_advanced"
	# get "/tables.html" => "static#tables"
	# get "/tables_dynamic.html" => "static#tables_dynamic"
	# get "/general_elements.html" => "static#general_elements"
	# get "/media_gallery.html" => "static#media_gallery"
	# get "/typography.html" => "static#typography"
	# get "/icons.html" => "static#icons"
	# get "/glyphicons.html" => "static#glyphicons"
	# get "/widgets.html" => "static#widgets"
	# get "/invoice.html" => "static#invoice"
	# get "/inbox.html" => "static#inbox"
	# get "/calendar.html" => "static#calendar"
	# get "/chartjs.html" => "static#chartjs"
	# get "/chartjs2.html" => "static#chartjs2"
	# get "/morisjs.html" => "static#morisjs"
	# get "/echarts.html" => "static#echarts"
	# get "/other_charts.html" => "static#other_charts"
	# get "/fixed_sidebar.html" => "static#fixed_sidebar"
	# get "/fixed_footer.html" => "static#fixed_footer"
	# get "/kitchen_sink" => "static#kitchen_sink"
	# get "/kitchen8_sink" => "static#kitchen8_sink"
  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  	
  	#--- Only for API calls---
	namespace :api, defaults: {format: 'json'} do
		namespace :v1 do
			resources :devices do
				get 'save_data' , :on => :collection
			end
		end
	end

	resources :devices do
		post 'update_user_device', on: :collection
	end

	resources :users do
		get 'assign_device', on: :collection
	end

end

app/models/user.rb
class User < ApplicationRecord
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
	
	has_many :devices, :through => :user_devices
	has_many :user_devices

	def fullname
    	full_name = ""
    	if self.first_name && self.last_name
    		full_name = self.first_name.concat(" ") + self.last_name
    	elsif self.first_name && !self.last_name
    		full_name = self.first_name
    	elsif !self.first_name && self.last_name
    		full_name = self.last_name
    	else
    		full_name = "Guest User"
    	end
    	
    	full_name
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index

		respond_to do |format|
			format.html { }
		end

	end

	def show
		
	end

	def assign_device

		@devices_list = Device.where(:status => "Active").order(:id)
		@observer = User.find(params[:observer_id])
		render "users/admin/assign_device"
	end

end

app/helpers/users_helper.rb
module UsersHelper

	def request_render(user)
		if user.is_admin

			@observer_list = User.where(:is_admin => false, :status => "Active").order(:id)
			@devices_list = Device.where(:status => "Active")
			render partial: "users/admin/show"

		else

			render partial: "users/observer/show"
		end
	end

end

app/views/users/admin/_devices_list.html.erb
<tr>
	<td><%= @devices_list[item].id %></td>
	<td><%= @devices_list[item].name %></td>
	<td><%= @devices_list[item].model %></td>
	<td><%= @devices_list[item].device_id %></td>
	<td><%= @devices_list[item].place %></td>
	<td><%= check_box_tag "device_ids[]", @devices_list[item].id, @devices_list[item].users.exists?(@observer.id)%></td>
	
</tr>

app/views/users/admin/_observer_list.html.erb
<tr>
	<td><%= @observer_list[item].id %></td>
	<td><%= @observer_list[item].first_name%> <%= @observer_list[item].last_name%></td>
	<td><%= @observer_list[item].contact_number %></td>
	<td><%= @observer_list[item].status %></td>
	<td><%= @observer_list[item].device_ids.sort %></td>
	<td>
		<%= link_to("Add / Remove Device", {:action => 'assign_device', :observer_id => @observer_list[item].id}, :class => 'btn-info btn') %>
	</td>
</tr>

app/views/users/admin/_show.html.erb
<%#= link_to("Devices list", devices_path, :class => 'btn-primary btn') %><br/><br/>
<table class="table table-striped table-bordered table-hover dataTables-example" >
    <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Contact Number</th>
            <th>Status</th>
            <th>Device Accessable</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <% if !@observer_list.blank? %>
            <% (0..(@observer_list.length - 1)).each do |i| %>
                <%= render :partial=>"users/admin/observer_list", :locals => {:item => i} %>
            <% end %>
        <% end %>
    </tbody>
</table>
<div class="clearfix"></div>

<!-- show device list to give permissions for users to monitor devices -->

<%= content_for :javascript do -%>
    <script type="text/javascript">
    	$(document).ready(function() {

    		$(".assign-device-to-user").click(function(){
        		// $(".device-select-modal").removeClass("hide");
                // alert($(this).attr('data-value'));
   		 	});

   		 	$(".update-user-devices").click(function(){
   		 		// $(".device-select-modal").addClass("hide");
   		 	});
    	});
    </script>
<% end -%>

app/views/users/admin/assign_device.html.erb
<div class="device-select-modal">
	<%= form_tag update_user_device_devices_path, :method => :post do %>
		<%= hidden_field_tag :observer_id , @observer.id %>
		<%= hidden_field_tag "device_ids[]", nil %>
		<table class="table table-striped table-bordered table-hover dataTables-example" >
		    <thead>
		        <tr>
		        	<th>#</th>
		            <th>Name</th>
		            <th>Model</th>
		            <th>Device id</th>
		            <th>Place</th>
		            <th>Select</th>
		        </tr>
		    </thead>
		    <tbody>
		        <% if !@devices_list.blank? %>
		            <% (0..(@devices_list.length - 1)).each do |i| %>
		                <%= render :partial=>"users/admin/devices_list", :locals => {:item => i} %>
		            <% end %>
		        <% end %>
		    </tbody>
		</table>

		<%= submit_tag("Update", :class => "btn-primary btn") %>
	<% end %>

</div>